name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile
        run: make deb -j16
      - name: Archive ld64
        uses: actions/upload-artifact@v2
        with:
          name: ld64
          path: |
            ld64
            ld64*.deb
      - name: Archive cctools-strip
        uses: actions/upload-artifact@v2
        with:
          name: cctools-strip
          path: |
            cctools-strip
            cctools-strip*.deb
