name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: make deb
      - uses: actions/upload-artifact@v2
        with:
          name: ld64
          path: |
            ld64
            *.deb
