name: CI

on:
  # Trigger on all pushes and pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch glibc
        run: |
          mkdir -p /tmp/ld64
          cd /tmp/ld64
          wget 'https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+build/19412132/+files/libc6_2.23-0ubuntu11.2_amd64.deb'
          dpkg-deb -x 'libc6_2.23-0ubuntu11.2_amd64.deb' libc6
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile
        run: LDFLAGS='/tmp/ld64/libc6/lib/x86_64-linux-gnu/libc.so.6 /tmp/ld64/libc6/lib/x86_64-linux-gnu/libm.so.6 /tmp/ld64/libc6/lib/x86_64-linux-gnu/libdl.so.2 /tmp/ld64/libc6/lib/x86_64-linux-gnu/libpthread.so.0' make deb
      - name: Archive ld64
        uses: actions/upload-artifact@v2
        with:
          name: ld64
          path: |
            ld64
            ld64*.deb
      - name: Archive cctools-strip
        uses: actions/upload-artifact@v2
        with:
          name: cctools-strip
          path: |
            cctools-strip
            cctools-strip*.deb
